### ISSUE TITLE
How to use your code?

### ISSUE THREAD

**Issue by jordan-gillard** [webhue/appannie#2]
Hey guys, how do I use appannie? I tried pip installing to no avail. Should I fork the entire repo and build a project with all your code in it?

**Comment by mbodea** [comment]
This library is currently not maintained, so forking the library would be advisable.

Alternatively you could install it like this:
```
pip install git+git://github.com/webhue/appannie.git
```
If you are going this route feel free to submit any fixes you find while using it.
